### ISSUE TITLE
Dependency conflict while installing 1.4.1.2

### ISSUE THREAD

**Issue by tac-tics** [skogsbaer/hscurses#21]
Any advice on resolving the following error?

    tac-tics@sagerbox:~/test/ncurses$ cabal install hscurses-1.4.1.2
    Resolving dependencies...
    cabal: Could not resolve dependencies:
    trying: hscurses-1.4.1.2 (user goal)
    trying: base-4.7.0.1/installed-e4b... (dependency of hscurses-1.4.1.2)
    next goal: unix (dependency of hscurses-1.4.1.2)
    rejecting: unix-2.7.0.1/installed-0d8..., 2.7.0.1, 2.7.0.0 (conflict: hscurses
    => unix>=2.4 && <2.7)
    rejecting: unix-2.6.0.1, 2.6.0.0 (conflict: base==4.7.0.1/installed-e4b...,
    unix => base>=4.2 && <4.7)
    rejecting: unix-2.5.1.1, 2.5.1.0 (conflict: base==4.7.0.1/installed-e4b...,
    unix => base>=4.2 && <4.6)
    rejecting: unix-2.5.0.0 (conflict: base==4.7.0.1/installed-e4b..., unix =>
    base>=4.2 && <4.5)
    rejecting: unix-2.4.2.0, 2.4.1.0 (conflict: base==4.7.0.1/installed-e4b...,
    unix => base>=4.2 && <4.4)
    rejecting: unix-2.4.0.2, 2.4.0.1 (conflict: base==4.7.0.1/installed-e4b...,
    unix => base>=4.2 && <4.3)
    rejecting: unix-2.4.0.0 (conflict: base==4.7.0.1/installed-e4b..., unix =>
    base>=4.1 && <4.3)
    rejecting: unix-2.3.2.0, 2.3.1.0, 2.3.0.0, 2.2.0.0, 2.0 (conflict: hscurses =>
    unix>=2.4 && <2.7)
    Dependency tree exhaustively searched.

    Note: when using a sandbox, all packages are required to have consistent
    dependencies. Try reinstalling/unregistering the offending packages or
    recreating the sandbox.

**Comment by skogsbaer** [comment]
I just uploaded 1.4.2.0 to hackage. Sorry for taking such a long time.
