### ISSUE TITLE
Read with timeout ,`wtimeout`?

### ISSUE THREAD

**Issue by sqd** [skogsbaer/hscurses#25]
Seems that there isn't a binding for `wtimeout`, so it's impossible to read a char with timeout. (Return the result if one is inputted before timeout, otherwise return an error)

**Comment by sqd** [comment]
It seems that I have misunderstood the document of `timeout` until I look into the source. It does need clarification though.

**Comment by yaxu** [comment]
@sqd I realise this was nearly a decade ago, but I don't suppose you remember how you resolved how to read a char with timeout? :)

**Comment by sqd** [comment]
Sorry I have no idea how/whether I resolved this :-(. Have you tried setting `notimeout` to false?

**Comment by yaxu** [comment]
@sqd Thanks for responding! I just solved it by using `getch` rather than `getCh`. I'll get back to you in 10 years with another question ;)
